import { useMemo, useRef } from 'react'
import FiltersBar from '../components/FiltersBar'
import KpiCard from '../components/KpiCard'
import { useData } from '../lib/data'
import { computeKPIs, computeHealthScore, getFilteredData } from '../lib/analytics'
import { exportNodeToPdf } from '../lib/exportPdf'

export default function Scorecard() {
  const { deliveries, incidents } = useData()
  const wrapRef = useRef(null)
  const { del, inc } = useMemo(() => getFilteredData(), [deliveries, incidents])
  const kpis = useMemo(() => computeKPIs({ del, inc }), [del, inc])
  const health = useMemo(() => computeHealthScore(kpis), [kpis])

  return (
    <div className="space-y-4">
      <div className="card p-4 flex items-start justify-between gap-4 flex-col lg:flex-row">
        <div>
          <h1 className="text-xl font-extrabold">KPI Scorecard Export</h1>
          <div className="text-sm text-slate-500 mt-1">Print-ready PDF for partners and internal QA (based on filters).</div>
        </div>
        <div className="no-print">
          <button className="btn btn-primary" onClick={() => exportNodeToPdf(wrapRef.current, 'Guicopac-Scorecard.pdf')}>Export PDF</button>
        </div>
      </div>

      <FiltersBar />

      <div ref={wrapRef} className="space-y-4">
        <div className="card p-4">
          <div className="text-xs text-slate-500 font-extrabold tracking-widest">HEALTH SCORE</div>
          <div className="mt-1 text-4xl font-extrabold">{health.toFixed(0)}<span className="text-base text-slate-500">/100</span></div>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-5 gap-4">
          {kpis.map((k) => (
            <KpiCard key={k.key} kpi={k} />
          ))}
        </div>

        <div className="card p-4">
          <div className="font-extrabold">Footer</div>
          <div className="text-sm text-slate-500 mt-1">Generated by Guicopac LLC internal operations dashboard.</div>
        </div>
      </div>
    </div>
  )
}
